add embeddings space component
theam/eLLMental pull request #16
Opened 2023-08-30 10:49 UTC by juanjoman

2023-08-30 10:56 UTC, NickSeagull approved these changes

2023-08-30 11:16 UTC, javiertoledo requested changes
Great work! I left a couple of comments:

* Let's make generation methods private and remove them from the documentation
* Let's discuss a bit about error handling and logging. It could make sense to create a small error handler class that help us homogenize how we handle them project-wide. We should avoid masking unknown errors and log messages in the correct log level.

2023-08-30 11:16 UTC, javiertoledo commented on docs-site/docs/03_components/02_embeddings_space.md
> +Embedding embedding = embeddingsSpace.save(sampleText);
💣 🚀

2023-08-30 11:16 UTC, javiertoledo commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +    }
I think that we no longer need to make generation methods public. Without the vector arithmetic, there's no reason to expose embedding objects to the user through this interface anymore, because even search calculates the embedding for the reference text internally...

2023-08-30 11:16 UTC, javiertoledo commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +        }
I'm not sure if capturing exceptions here makes sense because capturing _any_ runtime exception can mask errors and make troubleshooting more challenging. If we want to log the error, that's a good idea, but then we should re-raise the original exception or generate a new one, wrapping the original one. Also, if Java supports log levels, these logs must probably be `debug` level to avoid stuffing production logs.

2023-08-30 11:16 UTC, javiertoledo commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +            return null;
I've created a `MissingRequiredCredentialException` in https://github.com/theam/eLLMental/pull/15/files#diff-76b05f415c5a32450bc4c8092ca7a23ac0c019751b652a40173c696823a6bda4R4-R8

Not sure if it makes sense to capture Pinecone exceptions or is better to let them go through though

2023-08-30 11:23 UTC, juanjoman commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +        }
I'll remove the try catchs then, we can detect if this is needed in the future :P

2023-08-30 12:14 UTC, mnlx approved these changes
LGTM!

2023-08-31 13:14 UTC, javiertoledo approved these changes
LGTM. Will we wait for the test to be implemented here or you rather work on it in a future PR?

2023-08-31 13:14 UTC, javiertoledo commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +    }
I like private methods at the bottom of the class because when we read a class we tend to look for public methods first, but no need to change this now.

2023-08-31 13:14 UTC, javiertoledo commented on modules/embeddingsspace/src/main/java/com/theagilemonkeys/ellmental/embeddingsspace/EmbeddingsSpaceComponent.java
> +
The extra whitespace triggers OCD feelings 😅. Maybe we can activate a default linter to take all these little details into account 🤔

2023-08-31 13:26 UTC, juanjoman commented
Test will be done here -> https://github.com/theam/eLLMental/pull/20. So I'm merging this 🎉

2023-08-31 13:26 UTC, merged