use namespace from pinecone store constructor
theam/eLLMental pull request #25
Opened 2023-09-04 10:41 UTC by juanjoman

2023-09-04 10:46 UTC, javiertoledo approved these changes

2023-09-05 15:14 UTC, mnlx requested changes
Only issue is with the comment in the simplejava code. The rest looks good.

2023-09-05 15:14 UTC, mnlx commented on examples/simplejava/src/main/java/com/theagilemonkeys/ellmental/helloworld/Main.java
> -        // Step 1: generate embeddings from input string
Shouldn't we change the comment or delete the others ones. Since it's a numbered list.

2023-09-05 15:23 UTC, juanjoman commented on examples/simplejava/src/main/java/com/theagilemonkeys/ellmental/helloworld/Main.java
> -        // Step 1: generate embeddings from input string
I think I'm not understanding @mnlx , do you mean to keep those comments? 😮

2023-09-05 15:27 UTC, mnlx approved these changes
LGTM!

2023-09-06 07:45 UTC, merged