add text generation module
theam/eLLMental pull request #28
Opened 2023-09-05 10:07 UTC by juanjoman

2023-09-05 15:07 UTC, mnlx approved these changes
LGTM!

2023-09-05 15:53 UTC, javiertoledo requested changes
@juanjoman I think we should try to make the interface a bit more abstract, avoiding exposing the model's implementation details or dependencies to the end user. I'll create a PR with some ideas.

2023-09-05 15:53 UTC, javiertoledo commented on docs-site/docs/03_components/03_text_generation.md
> +The text generation module aims to give the user an abstraction to use any model to give final answers to user questions.
```suggestion
The text generation module aims to give the user an abstraction to use Large Language Models (LLMs) that, given a prompt, tries to complete it with the most useful text possible. LLMs can be used for a very wide range of use cases, including summarizing text, drafting an essay, or getting answers for general knowledge questions.

If you have a large corpus of text indexed as embeddings (For instance, using the [`EmbeddingsSpaceComponent`](./embeddings_space)), you can build a question answering system by injecting the best matches as part of the text generation prompt.
```

2023-09-05 15:53 UTC, javiertoledo commented on docs-site/docs/03_components/03_text_generation.md
> +You can use the `OpenAiTextGenerationService` to work with openAI chat messaging system:
```suggestion
You can use the `OpenAiTextGenerationModel` to work with OpenAI's models like [GPT-3](https://openai.com/blog/gpt-3-apps) or [GPT-4](https://openai.com/gpt-4):
```

2023-09-05 15:53 UTC, javiertoledo commented on docs-site/docs/03_components/03_text_generation.md
> +Double temperature = 0.1;
```suggestion
// In this example we create a prompt that simulates a chat to make the LLM respond the question asked.
Double temperature = 0.1;
```

2023-09-05 15:53 UTC, javiertoledo commented on docs-site/docs/03_components/03_text_generation.md
> +```
We should try to avoid exposing this to the end user.

2023-09-05 17:16 UTC, javiertoledo commented on docs-site/docs/03_components/03_text_generation.md
> +The text generation module aims to give the user an abstraction to use any model to give final answers to user questions.
I'll send the suggestions as part of my PR

2023-09-06 09:42 UTC, javiertoledo approved these changes
Looks great, I left a couple of minor notes. There's a class we might not need anymore and we should probably discuss a bit about error handling, but that discussion shouldn't block this PR 😜

2023-09-06 09:42 UTC, javiertoledo commented on modules/textgeneration/src/main/java/com/theagilemonkeys/ellmental/textgeneration/openai/OpenAiConfig.java
> +}
Are we using this class? It seems we're directly using the OpenAiModels enum everywhere, so we may want to delete it.

2023-09-06 09:42 UTC, javiertoledo commented on modules/textgeneration/src/main/java/com/theagilemonkeys/ellmental/textgeneration/openai/errors/Constants.java
> +}
We'll need to agree on a consistent way to handle error messages. The file of constants is a way, but it makes us constantly navigate to this file and look for the right constant every time we need to edit an error message. One thing we could do is creating specific exception classes with the error message embedded. This way, the error message is always in context and easy to edit, and we never repeat the same message in the codebase:

```java
package com.theagilemonkeys.ellmental.textgeneration.openai.errors;

public class NoContentFoundException extends RuntimeException {
    private static final String MESSAGE_FORMAT = "No response could be found for your request for messages %s";

    public NoContentFoundException(String messageDetail) {
        super(String.format(MESSAGE_FORMAT, messageDetail));
    }
}
```

This way instead of doing something like:

```java
if (!contentExists) {
    throw new RuntimeException(String.format("No response could be found for your request for messages %s", messageDetail));
}
```

We can do:

```java
if (!contentExists) {
    throw new NoContentFoundException(messages);
}
```

Let's discuss this and work on a new PR to apply the decision made 😜

2023-09-06 11:25 UTC, merged