Changed libraries to start using Java 17 and not Kotlin
theam/eLLMental pull request #6
Opened 2023-08-14 21:17 UTC by mnlx

2023-08-17 09:17 UTC, juanjoman requested changes
Just added a couple of suggestions and questions, nice work!!

2023-08-17 09:17 UTC, juanjoman commented on gradle.properties
> +#openAiServiceVersion=0.15.0
can we remove the kotlin properties? Why are the rest commented?

2023-08-17 09:17 UTC, juanjoman commented on modules/embeddingsgeneration/build.gradle
> +version = 'unspecified'
I think we can set 0.0.1-SNAPSHOT for now 😄

2023-08-17 09:17 UTC, juanjoman commented on modules/embeddingsgeneration/src/main/java/com/theagilemonkeys/ellmental/embeddingsgeneration/Embedding.java
> +}
Why is the embedding empty? 😮

2023-08-17 09:17 UTC, juanjoman commented on modules/embeddingsstore/build.gradle
> +version = 'unspecified'
same about the version

2023-08-17 09:17 UTC, juanjoman commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/Embedding.java
> +}
same for the empty object

2023-08-17 09:40 UTC, mnlx commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/Embedding.java
> +}
These where just the scafolding for the initial setup. At first I just wanted to validate if the project structure was as expected. I just pushed the updates on these with their non empty versions.

2023-08-17 09:40 UTC, mnlx commented on modules/embeddingsgeneration/src/main/java/com/theagilemonkeys/ellmental/embeddingsgeneration/Embedding.java
> +}
Answered below

2023-08-17 09:41 UTC, mnlx commented on modules/embeddingsgeneration/build.gradle
> +version = 'unspecified'
Updated with the latest push

2023-08-17 09:41 UTC, mnlx commented on gradle.properties
> +#openAiServiceVersion=0.15.0
I'll remove them in the next push

2023-08-17 09:45 UTC, mnlx commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/pinecone/PineconeEmbeddingsStore.java
> +                .header("Api-Key", "1c13987f-1d13-4373-8655-f739089de6af")
This API key is from my personal account, I'll delete them once I implement dotenv or env variables.

2023-08-17 09:46 UTC, mnlx commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/pinecone/UpsertVectorSchema.java
> +//class Schema {
Removing this

2023-08-17 10:30 UTC, juanjoman commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/pinecone/UpsertVectorSchema.java
> +    // Getters and setters
You can have a look at lombok if you want to get rid of a lot of code 😋 -> https://www.baeldung.com/intro-to-project-lombok

2023-08-17 16:24 UTC, NickSeagull approved these changes
Apart of deleting dead code or env keys, lgtm!

2023-08-18 07:31 UTC, adrian-lorenzo approved these changes
The same as Nick. Apart from that, LGTM!

2023-08-20 09:40 UTC, mnlx commented on modules/embeddingsstore/src/main/java/com/theagilemonkeys/ellmental/embeddingsstore/pinecone/UpsertVectorSchema.java
> +    // Getters and setters
I heard of this library before, never new it was used for this. So much easier. I'm going to create a task to start using Lombok.

2023-08-21 10:32 UTC, merged